name: AutoSave Markdown

on:
  push:
    paths:
      - 'docs/**/*.md'

jobs:
  autosave:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Git identity
        run: |
          git config user.name "월이-자동저장"
          git config user.email "auto@월이.ai"

      - name: Commit and Push
        run: |
          git add docs/*.md
          git commit -m "자동 저장: 최신 .md 파일 업데이트" || echo "Nothing to commit"
          git push
